version: '3'
services:

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper
    volumes:
      - /home/api-dev/zookeeper/data:/opt/zookeeper-3.4.13/data
    ports:
      - "2181"

  kafka:
    hostname: kafka
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    environment:
      KAFKA_CREATE_TOPICS: "telemetry:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: api-lxvdev.westus3.cloudapp.azure.com # docker-machine ip
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://api-lxvdev.westus3.cloudapp.azure.com:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/api-dev/kafka:/kafka/kafka-logs
    ports:
      - "9092:9092"
    expose:
      - '9092'
    depends_on:
      - "zookeeper"

  database:
    hostname: database
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'telemetry'
      MYSQL_USER: 'storage'
      MYSQL_PASSWORD: store
      MYSQL_ROOT_PASSWORD: rootbeer
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '3306'
    networks:
      - 'api.network'

  receiver:
    hostname: receiver
    build: 
      context: ../receiver
    image: api_receiver:latest
    environment:
      TARGET_ENV: prod
      SERVER_HOST: api-lxvdev.westus3.cloudapp.azure.com
      SERVER_PORT: 9092
    volumes:
      - /home/api-dev/config/receiver:/config
      - /home/api-dev/logs:/logs
    ports:
      - '8080'
    networks:
      - 'api.network'
    depends_on:
      - "kafka"
      - "storage"

  storage:
    hostname: storage
    build: 
      context: ../storage
    image: api_storage:latest
    environment:
      TARGET_ENV: prod
      SERVER_HOST: api-lxvdev.westus3.cloudapp.azure.com
      SERVER_PORT: 9092
      DB_HOST: database
      DB_PORT: 3306
    volumes:
      - /home/api-dev/config/storage:/config
      - /home/api-dev/logs:/logs
    ports:
      - '8090'
    networks:
      - 'api.network'
    depends_on:
      - "kafka"
      - "database"

  processing:
    hostname: processing
    build: 
      context: ../processing
    image: api_processing:latest
    environment:
      TARGET_ENV: prod
      # SERVER_HOST: api-lxvdev.westus3.cloudapp.azure.com
      # SERVER_PORT: 80
    volumes:
      - /home/api-dev/config/processing:/config
      - /home/api-dev/logs:/logs
      - stats:/src/data
    ports:
      - '8100'
    networks:
      - 'api.network'
    depends_on:
      - "storage"

  audit_log:
    hostname: audit_log
    build: 
      context: ../log_audit
    image: api_auditlog:latest
    environment:
      TARGET_ENV: prod
      SERVER_HOST: api-lxvdev.westus3.cloudapp.azure.com
      SERVER_PORT: 9092
    volumes:
      - /home/api-dev/config/audit_log:/config
      - /home/api-dev/logs:/logs
    ports:
      - '8110'
    networks:
      - 'api.network'
    depends_on:
      - "kafka"

  dashboard:
    hostname: dashboard
    build: 
      context: ../ui-dashboard
    image: api_dashboard:latest
    ports:
      - '3000'
    networks:
      - 'api.network'
    depends_on:
      - "processing"
      - "audit_log"

  nginx:
    image: nginx:latest
    volumes:
      - /home/api-dev/nginx:/etc/nginx
    ports:
      - '80:80'
    networks:
      - 'api.network'
    depends_on:
      - "receiver"
      - "storage"
      - "processing"
      - "audit_log"
      - "dashboard"

volumes:
  mysql:
  stats:

networks:
  api.network:
