version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "telemetry:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: api.lxvdev.xyz # docker-machine ip
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://api.lxvdev.xyz:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
  db:
    image: mysql:8
    restart: always
    volumes:
      - my-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'telemetry'
      MYSQL_USER: 'storage'
      MYSQL_PASSWORD: store
      MYSQL_ROOT_PASSWORD: rootbeer
    ports:
      - '3306:3306'
    expose:
      - '3306'

volumes:
  my-db: