---
version: '3'
  
services:
  receiver:
    build: 
      context: ../receiver
    environment:
      SERVER_HOST: api-lxvdev.westus3.cloudapp.azure.com
      SERVER_PORT: 9092
      DATA_TOPIC: 'telemetry'
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      # - "kafka"
      - "storage"
  
  storage:
    build: 
      context: ../storage
    environment:
      SERVER_HOST: api-lxvdev.westus3.cloudapp.azure.com
      SERVER_PORT: 9092
      DATA_TOPIC: 'telemetry'
      DB_HOST: api-lxvdev.westus3.cloudapp.azure.com
      DB_PORT: 3306
      DB_NAME: telemetry
      DB_USERNAME: storage
      DB_PASSWORD: store
    ports:
      - '8090:8090'
    # depends_on:
      # - "kafka"
      # - "db"

  processing:
    build: 
      context: ../processing
    environment:
      SERVER_URL: http://localhost:8090
    ports:
      - '8100:8100'
    depends_on:
      - "storage"

  auditlog:
    build: 
      context: ../log_audit
    environment:
      SERVER_HOST: api-lxvdev.westus3.cloudapp.azure.com
      SERVER_PORT: 9092
      DATA_TOPIC: 'telemetry'
    ports:
      - '8110:8110'
    