---
openapi: 3.0.3
info:
  title: OpenAtmos - OpenAPI 3.0
  description: |-
    This is an air quality monitoring API that meets OpenAPI 3.0 specification.
    The API receives environmental data from IoT sensors that measures data on ambient temperature, CO<sub>2</sub>, and PM<sub>2.5</sub>.
  contact:
    email: dev@openatmos.com
  license:
    name: GNU General Public License (GPLv3)
    url: https://www.gnu.org/licenses/gpl-3.0.html
  version: '2.0.0'
tags:
- name: System
  description: System service health
paths:
  /health:
    get:
      tags:
        - System
      summary: gets system health
      operationId: app.get_health
      description: gets last system health check
      responses:
        '200':
          description: sucessfully returned a list of data
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/HealthCheck'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    HealthCheck:
      type: object
      required:
        - receiver
        - storage
        - auditlog
        - processing
        - last_updated
      properties:
        receiver:
          type: integer
          example: 200
        storage:
          type: integer
          example: 200
        auditlog:
          type: integer
          example: 200
        processing:
          type: integer
          example: 200
        last_updated:
          type: string
          format: date-time
          example: 2022-12-31 12:34:56.000000
